version: '3.8'

services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${NEXTCLOUD_BACKUP_DIR}:/var/www/html/data/backup_dir
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      APACHE_PORT: 11000
      FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms1024M -Xmx1024M"
      NEXTCLOUD_UPLOAD_LIMIT: 1028G
      NEXTCLOUD_MAX_TIME: 7200
      NEXTCLOUD_MEMORY_LIMIT: 1028M
      NEXTCLOUD_ENABLE_DRI_DEVICE: true
      SKIP_DOMAIN_VALIDATION: false
      TALK_PORT: 3478
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DATADIR}

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer